// Sample data for the Radio collection
const radioTracks = [
  {
    title: 'Aurora',
    type: 'track',
    sourceType: 'spotify',
    source: { externalLink: 'https://open.spotify.com/track/123abc' },
    bpm: 128,
    key: 'C#',
    duration: 420,
    artist: [1], // Assume 1 maps to Alex Stein
    genres: [1], // Assume 1 maps to Techno
    recordLabel: 'Drumcode',
    releaseDate: '2023-07-15',
    description: 'A powerful, melodic techno track.',
    image: null, // Placeholder for cover image
    slug: 'aurora',
  },
  {
    title: 'Neural Collapse',
    type: 'track',
    sourceType: 'soundcloud',
    source: { externalLink: 'https://soundcloud.com/track/456def' },
    bpm: 130,
    key: 'D',
    duration: 390,
    artist: [2], // Assume 2 maps to Victor Ruiz
    genres: [1],
    recordLabel: 'Filth on Acid',
    releaseDate: '2022-11-12',
    description: 'A dark, driving piece with pulsating rhythms.',
    image: null,
    slug: 'neural-collapse',
  },
  {
    title: 'Afterlife',
    type: 'track',
    sourceType: 'youtube',
    source: { externalLink: 'https://youtube.com/watch?v=789ghi' },
    bpm: 126,
    key: 'F',
    duration: 460,
    artist: [3], // Assume 3 maps to ARTBAT
    genres: [1],
    recordLabel: 'Afterlife',
    releaseDate: '2021-06-20',
    description: 'A haunting, euphoric track with deep bass.',
    image: null,
    slug: 'afterlife',
  },
  {
    title: 'Eclipse',
    type: 'track',
    sourceType: 'spotify',
    source: { externalLink: 'https://open.spotify.com/track/987jkl' },
    bpm: 129,
    key: 'G',
    duration: 400,
    artist: [4], // Assume 4 maps to Charlotte de Witte
    genres: [1],
    recordLabel: 'KNTXT',
    releaseDate: '2023-02-01',
    description: 'An energetic techno anthem with a relentless pace.',
    image: null,
    slug: 'eclipse',
  },
  {
    title: 'Pulse',
    type: 'track',
    sourceType: 'internal',
    source: { internalUpload: 123 }, // Assume 123 maps to an internal upload ID
    bpm: 132,
    key: 'E',
    duration: 450,
    artist: [1],
    genres: [1],
    recordLabel: 'Terminal M',
    releaseDate: '2020-09-30',
    description: 'A high-energy track with a signature rolling bassline.',
    image: null,
    slug: 'pulse',
  },
  {
    title: 'Stratosphere',
    type: 'track',
    sourceType: 'beatport',
    source: { externalLink: 'https://www.beatport.com/track/654mno' },
    bpm: 128,
    key: 'A#',
    duration: 415,
    artist: [5], // Assume 5 maps to Enrico Sangiuliano
    genres: [1],
    recordLabel: 'Drumcode',
    releaseDate: '2019-03-12',
    description: 'A spacey techno journey with intricate textures.',
    image: null,
    slug: 'stratosphere',
  },
  {
    title: 'Genesis',
    type: 'set',
    sourceType: 'youtube',
    source: { externalLink: 'https://youtube.com/watch?v=abc321' },
    bpm: null, // Not applicable for a set
    key: null,
    duration: 3600,
    artist: [1],
    genres: [1],
    recordLabel: null,
    releaseDate: '2024-01-15',
    description: 'A one-hour live techno set by the DJ.',
    image: null,
    slug: 'genesis-set',
  },
  {
    title: 'Reverie',
    type: 'track',
    sourceType: 'bandcamp',
    source: { externalLink: 'https://bandcamp.com/track/987stu' },
    bpm: 127,
    key: 'D#',
    duration: 430,
    artist: [6], // Assume 6 maps to Amelie Lens
    genres: [1],
    recordLabel: 'Lenske',
    releaseDate: '2022-05-25',
    description: 'A hypnotic track with layered melodies.',
    image: null,
    slug: 'reverie',
  },
  {
    title: 'Dreamstate',
    type: 'track',
    sourceType: 'spotify',
    source: { externalLink: 'https://open.spotify.com/track/765vwx' },
    bpm: 125,
    key: 'G#',
    duration: 425,
    artist: [7], // Assume 7 maps to Tale of Us
    genres: [1],
    recordLabel: 'Afterlife',
    releaseDate: '2021-11-08',
    description: 'A cinematic, emotional journey in techno.',
    image: null,
    slug: 'dreamstate',
  },
  {
    title: 'Momentum',
    type: 'track',
    sourceType: 'soundcloud',
    source: { externalLink: 'https://soundcloud.com/track/654yz' },
    bpm: 129,
    key: 'B',
    duration: 410,
    artist: [8], // Assume 8 maps to Reinier Zonneveld
    genres: [1],
    recordLabel: 'Filth on Acid',
    releaseDate: '2020-12-10',
    description: 'A hard-hitting techno track with a driving bassline.',
    image: null,
    slug: 'momentum',
  },
]

export default radioTracks
